const Message =  {
    channel:  { //TextChannel
      type: 'text',
      deleted: false,
      id: '739495178481434687',
      name: 'general',
      rawPosition: 0,
      parentID: '739495178481434685',
      permissionOverwrites: Collection [Map] {},
      topic: null,
      nsfw: undefined,
      lastMessageID: '739607893522907216',
      rateLimitPerUser: 0,
      lastPinTimestamp: null,
      guild: Guild {
        members: [GuildMemberManager],
        channels: [GuildChannelManager],
        roles: [RoleManager],
        presences: [PresenceManager],
        voiceStates: [VoiceStateManager],
        deleted: false,
        available: true,
        id: '739495177990701077',
        shardID: 0,
        name: 'DDocs',
        icon: null,
        splash: null,
        region: 'brazil',
        memberCount: 2,
        large: false,
        features: [],
        applicationID: null,
        afkTimeout: 300,
        afkChannelID: null,
        systemChannelID: '739495178481434687',
        embedEnabled: undefined,
        premiumTier: 0,
        premiumSubscriptionCount: 0,
        verificationLevel: 'NONE',
        explicitContentFilter: 'DISABLED',
        mfaLevel: 0,
        joinedTimestamp: 1596405852248,
        defaultMessageNotifications: 'ALL',
        systemChannelFlags: [SystemChannelFlags],
        vanityURLCode: null,
        description: null,
        banner: null,
        rulesChannelID: null,
        publicUpdatesChannelID: null,
        ownerID: '233659457480032269',
        emojis: [GuildEmojiManager]
      },
      messages:  { //MessageManager
        cacheType: [Function: LimitedCollection],
        cache: [LimitedCollection [Map]],
        channel: [Circular]
      },
      _typing: Map {}
    },
    deleted: false,
    id: '739607893522907216',
    type: 'DEFAULT',
    content: 'hello',
    author: User {
      id: '233659457480032269',
      bot: false,
      username: 'Mancosky',
      discriminator: '4224',
      avatar: null,
      lastMessageID: '739607893522907216',
      lastMessageChannelID: '739495178481434687',
      flags: UserFlags { bitfield: 0 }
    },
    pinned: false,
    tts: false,
    nonce: '739607890830032896',
    system: false,
    embeds: [],
    attachments: Collection [Map] {},
    createdTimestamp: 1596406663066,
    editedTimestamp: null,
    reactions: ReactionManager {
      cacheType: [Function: Collection],
      cache: Collection [Map] {},
      message: [Circular]
    },
    mentions: MessageMentions {
      everyone: false,
      users: Collection [Map] {},
      roles: Collection [Map] {},
      _members: null,
      _channels: null,
      crosspostedChannels: Collection [Map] {}
    },
    webhookID: null,
    application: null,
    activity: null,
    _edits: [],
    flags: MessageFlags { bitfield: 0 },
    reference: null
  }